### ISSUE TITLE
Wrong password in config file result in clean exit with nothing happening

### ISSUE THREAD

**Issue by jorianvo** [030/n3dr#86]
**What happened**:
I put the wrong password in my `~/.n3dr.yaml` file.

**What you expected to happen**:
n3dr failing and providing a descriptive message that my authentication failed.

**How to reproduce it (as minimally and precisely as possible)**:
Put a dummy password in your `~/.n3dr.yaml` file and run the tool like:
`./n3dr-osx repositories -n <URL> -u <USER> -b -d`

**Anything else we need to know?**:

**Environment**:
- n3dr version (use `n3dr -v`): **Command does not work**
- OS (e.g: `cat /etc/os-release`): **MacOS**
- Kernel (e.g. `uname -a`): **Darwin MACC02S957AG8WP 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64**
- Others:

**Comment by 030** [comment]
@jorianvo Thank you for addressing this issue. It seems that an `else` clause is missing in the `cmd/repositories.go` and `cmd/backup.go` at `if resp.StatusCode != http.StatusOK {`. In order to solve this the logic from the both files should be moved to a separate file and an error should be returned if the authentication fails.

**Comment by 030** [comment]
@jorianvo could you test version 3.3.1 on MacOSX?
